version: "3.8"

services:
  db:
    image: mysql:8.0
    volumes:
      - todo_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
    ports:
      - 3310:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  web:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      # 開発用のイメージを作成する
      target: dev
    # フォアグラウンドで入力のための仮想端末が起動し続ける(プロセスが終了しない)
    tty: true
    # コンテナの標準入力をオープンにしたままにする
    stdin_open: true
    # バインドマウント
    volumes:
      - .:/go/src/app
    environment:
      DB: mysql
      DB_HOST: db
      DB_NAME: todo_db
      DB_USER: root
      DB_PASSWORD: password
      PORT: 3306
      # ホストの8080に来たリクエストをコンテナの8080に送る
    ports:
      - 8080:8080
    # 依存の向き「web → db」
    # dbを起動してからwebを起動する
    depends_on:
      - db

volumes:
  todo_db: